#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeManagement
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CafeDB")]
	public partial class CafeDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public CafeDBDataContext() : 
				base(global::CafeManagement.Properties.Settings.Default.CafeDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CafeDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CafeDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CafeDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CafeDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cafe> Cafes
		{
			get
			{
				return this.GetTable<Cafe>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cafe")]
	public partial class Cafe
	{
		private string _CafeID;

		private string _CafeName;

		private string _CafeType;

		private System.Nullable<System.DateTime> _OpeningDate;

		private System.Nullable<double> _PriceRange;

		public Cafe()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CafeID", DbType = "NVarChar(255) NOT NULL", CanBeNull = false)]
		public string CafeID
		{
			get
			{
				return this._CafeID;
			}
			set
			{
				if ((this._CafeID != value))
				{
					this._CafeID = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CafeName", DbType = "NVarChar(255)")]
		public string CafeName
		{
			get
			{
				return this._CafeName;
			}
			set
			{
				if ((this._CafeName != value))
				{
					this._CafeName = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CafeType", DbType = "NVarChar(255)")]
		public string CafeType
		{
			get
			{
				return this._CafeType;
			}
			set
			{
				if ((this._CafeType != value))
				{
					this._CafeType = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_OpeningDate", DbType = "DateTime")]
		public System.Nullable<System.DateTime> OpeningDate
		{
			get
			{
				return this._OpeningDate;
			}
			set
			{
				if ((this._OpeningDate != value))
				{
					this._OpeningDate = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_PriceRange", DbType = "Float")]
		public System.Nullable<double> PriceRange
		{
			get
			{
				return this._PriceRange;
			}
			set
			{
				if ((this._PriceRange != value))
				{
					this._PriceRange = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
